load("@bazel_features//:deps.bzl", "bazel_features_deps")
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
load("@io_grpc_grpc_java//:repositories.bzl", "io_grpc_grpc_proto")
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies")
load("@rules_proto//proto:setup.bzl", "rules_proto_setup")
load("@rules_python//python:repositories.bzl", "py_repositories")
load("//third_party/go:repositories.bzl", "go_deps")

def contrib_rules_jvm_gazelle_setup():
    bazel_features_deps()
    rules_pkg_dependencies()
    protobuf_deps()
    py_repositories()
    rules_proto_dependencies()
    rules_proto_setup()
    io_grpc_grpc_proto()
    go_deps()
