load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "fd14d9d8605ee4cb8ecf33ef2e329c65ec590a8f39941f75f5c71e5a1d22f89b",
    strip_prefix = "rules_jvm_external-762f94d8bf405d7250c8d20179acc69e01156581",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/762f94d8bf405d7250c8d20179acc69e01156581.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.0-jre",
        "junit:junit:4.13.1",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
