load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "cd7fa36bf98bd20f65f0383400c3c36585fe509de201a92a46d2f794b180cd77",
    strip_prefix = "rules_jvm_external-c8c8a8720c17a88a32d64995f251f61de4d1665a",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/c8c8a8720c17a88a32d64995f251f61de4d1665a.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.0-jre",
        "junit:junit:4.13.1",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
