load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "d1dcd42aa9afee37f2e00697ae348d586b72f8e40ee79ee55acb57cc257064ad",
    strip_prefix = "rules_jvm_external-7b439d1e1751d44916530a19806e86a2a105c03b",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/7b439d1e1751d44916530a19806e86a2a105c03b.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.0-jre",
        "junit:junit:4.13.1",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
