name: Gazelle Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gazelle_examples:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      # The windows-latest image comes with Java 8 but rules_jvm_external requires at least 11, so we install a newer JDK.
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel action cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Mount bazel repo cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel-repo"
          key: bazel-repo

      - name: bzlmod gazelle
        env:
          # Bazelisk will download bazel to here, ensure it is cached between runs.
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: (cd examples/gazelle && bazelisk --bazelrc=../../.github/workflows/ci.bazelrc run --enable_bzlmod //:gazelle && bazelisk --bazelrc=../../.github/workflows/ci.bazelrc test --enable_bzlmod //...)
